#include "save.hpp"

#include <fstream>

void read_save(save& sav, std::string path)
{
	std::ifstream file{path, std::ios::in | std::ios::binary};
	file.read(reinterpret_cast<char*>(&sav), sizeof(sav));
}
void write_save(const save& sav, std::string path)
{
	std::ofstream file{path, std::ios::in | std::ios::binary | std::ios::trunc};
	file.write(reinterpret_cast<const char*>(&sav), sizeof(sav));
}

int_value::int_value(const char* d, std::size_t i)
	: description{d}
	, index{i}
{
}

std::int32_t int_value::get_value(const save& s) const
{
	return s[index];
}

void int_value::set_value(save& s, std::int32_t val)
{
	s[index] = val;
}

bool_value::bool_value(const char* d, std::size_t i)
	: description{d}
	, index{i}
{
}

bool bool_value::get_value(const save& s)
{
	return s[index];
}

void bool_value::set_value(save& s, bool val)
{
	s[index] = val;
}

save_layout::save_layout()
	: elements{
		int_value{"Amount of plays"                        , 0},
		int_value{"Amount of deaths"                       , 1},
		int_value{"Normal wins"                            , 2},
		int_value{"Hell wins"                              , 3},
		int_value{"Related to deathmatch unlocks"          , 4},
		int_value{"Related to deathmatch unlocks"          , 5},
		int_value{"Related to deathmatch unlocks"          , 6},
		int_value{"High score"                             , 7},
		int_value{"Fastest time (ms)"                      , 8},
		int_value{"Average score"                          , 9},
		int_value{"Level before death"                     , 10},
		int_value{"Special level before death"             , 11},
		int_value{"Score before death"                     , 12},
		int_value{"Killed by"                              , 13},
		int_value{"Items before death"                     , 14},
		int_value{"Items before death"                     , 15},
		int_value{"Items before death"                     , 16},
		int_value{"Items before death"                     , 17},
		int_value{"Cave unlocked? (0 - 2)"                 , 134},
		int_value{"Shortcuts unlocked (0 - 6)"             , 135},
		bool_value{"Second favor completed"                 , 136},
		bool_value{"Place discovered: Mines"                , 265},
		bool_value{"Place discovered: Jungle"               , 266},
		bool_value{"Place discovered: Ice caves"            , 267},
		bool_value{"Place discovered: Temple"               , 268},
		bool_value{"Place discovered: Hell"                 , 269},
		bool_value{"Place discovered: Haunted castle"       , 270},
		bool_value{"Place discovered: Black market"         , 271},
		bool_value{"Place discovered: Worm"                 , 272},
		bool_value{"Place discovered: Mothership"           , 273},
		bool_value{"Place discovered: City of gold"         , 274},
		bool_value{"Creature discovered: Snake"             , 329},
		bool_value{"Creature discovered: Cobra"             , 330},
		bool_value{"Creature discovered: Bat"               , 331},
		bool_value{"Creature discovered: Spider"            , 332},
		bool_value{"Creature discovered: Spinner spider"    , 333},
		bool_value{"Creature discovered: Gaint spider"      , 334},
		bool_value{"Creature discovered: Skeleton"          , 335},
		bool_value{"Creature discovered: Scorpion"          , 336},
		bool_value{"Creature discovered: Caveman"           , 337},
		bool_value{"Creature discovered: Damsel"            , 338},
		bool_value{"Creature discovered: Shopkeeper"        , 339},
		bool_value{"Creature discovered: Tunnelman"         , 340},
		bool_value{"Creature discovered: Scarab"            , 341},
		bool_value{"Creature discovered: Tiki man"          , 342},
		bool_value{"Creature discovered: (Blue) frog"       , 343},
		bool_value{"Creature discovered: Fire (orange) frog", 344},
		bool_value{"Creature discovered: Gaint frog"        , 345},
		bool_value{"Creature discovered: Mantrap"           , 346},
		bool_value{"Creature discovered: Piranha"           , 347},
		bool_value{"Creature discovered: Old bitey"         , 348},
		bool_value{"Creature discovered: Killer bee"        , 349},
		bool_value{"Creature discovered: Queen bee"         , 350},
		bool_value{"Creature discovered: Snail"             , 351},
		bool_value{"Creature discovered: Monkey"            , 352},
		bool_value{"Creature discovered: Golden monkey"     , 353},
		bool_value{"Creature discovered: Jiang shi"         , 354},
		bool_value{"Creature discovered: Green knight"      , 355},
		bool_value{"Creature discovered: Black knight"      , 356},
		bool_value{"Creature discovered: Vampire"           , 357},
		bool_value{"Creature discovered: Ghost"             , 358},
		bool_value{"Creature discovered: Bacterium"         , 359},
		bool_value{"Creature discovered: Worm egg"          , 360},
		bool_value{"Creature discovered: Worm baby"         , 361},
		bool_value{"Creature discovered: Yeti"              , 362},
		bool_value{"Creature discovered: Yeti king"         , 363},
		bool_value{"Creature discovered: Mammoth"           , 364},
		bool_value{"Creature discovered: Alien"             , 365},
		bool_value{"Creature discovered: Ufo"               , 366},
		bool_value{"Creature discovered: Alien tank"        , 367},
		bool_value{"Creature discovered: Alien lord"        , 368},
		bool_value{"Creature discovered: Alien queen"       , 369},
		bool_value{"Creature discovered: Hawk man"          , 370},
		bool_value{"Creature discovered: Croc man"          , 371},
		bool_value{"Creature discovered: Magma man"         , 372},
		bool_value{"Creature discovered: Scorpion fly"      , 373},
		bool_value{"Creature discovered: Mummy"             , 374},
		bool_value{"Creature discovered: Anubis"            , 375},
		bool_value{"Creature discovered: Anubis II"         , 376},
		bool_value{"Creature discovered: Olmec"             , 377},
		bool_value{"Creature discovered: Vlad"              , 378},
		bool_value{"Creature discovered: Imp"               , 379},
		bool_value{"Creature discovered: Devil"             , 380},
		bool_value{"Creature discovered: Succubus"          , 381},
		bool_value{"Creature discovered: Horse head"        , 382},
		bool_value{"Creature discovered: Ox face"           , 383},
		bool_value{"Creature discovered: King yama"         , 384},
		bool_value{"Item discovered: Rope pile"             , 393},
		bool_value{"Item discovered: Bomb bag"              , 394},
		bool_value{"Item discovered: Bomb box"              , 395},
		bool_value{"Item discovered: Spectacles"            , 396},
		bool_value{"Item discovered: Climbing gloves"       , 397},
		bool_value{"Item discovered: Pitchers mitt"         , 398},
		bool_value{"Item discovered: Spring shoes"          , 399},
		bool_value{"Item discovered: Spike shoes"           , 400},
		bool_value{"Item discovered: Paste"                 , 401},
		bool_value{"Item discovered: Compass"               , 402},
		bool_value{"Item discovered: Mattock"               , 403},
		bool_value{"Item discovered: Boomerang"             , 404},
		bool_value{"Item discovered: Machete"               , 405},
		bool_value{"Item discovered: Crysknife"             , 406},
		bool_value{"Item discovered: Web gun"               , 407},
		bool_value{"Item discovered: Shotgun"               , 408},
		bool_value{"Item discovered: Freeze ray"            , 409},
		bool_value{"Item discovered: Plasma cannon"         , 410},
		bool_value{"Item discovered: Camera"                , 411},
		bool_value{"Item discovered: Teleporter"            , 412},
		bool_value{"Item discovered: Parachute"             , 413},
		bool_value{"Item discovered: Cape"                  , 414},
		bool_value{"Item discovered: Jetpack"               , 415},
		bool_value{"Item discovered: Shield"                , 416},
		bool_value{"Item discovered: Royal jelly"           , 417},
		bool_value{"Item discovered: Idol"                  , 418},
		bool_value{"Item discovered: Kapala"                , 419},
		bool_value{"Item discovered: Udjat eye"             , 420},
		bool_value{"Item discovered: Ankh"                  , 421},
		bool_value{"Item discovered: Hedjet"                , 422},
		bool_value{"Item discovered: Sceptre"               , 423},
		bool_value{"Item discovered: Book of the death"     , 424},
		bool_value{"Item discovered: Vlad's cape"           , 425},
		bool_value{"Item discovered: Vlad's amulet"         , 426},
		bool_value{"Trap discovered: Spike"                 , 457},
		bool_value{"Trap discovered: Arrow trap"            , 458},
		bool_value{"Trap discovered: Powder box"            , 459},
		bool_value{"Trap discovered: Boulder"               , 460},
		bool_value{"Trap discovered: Tiki trap"             , 461},
		bool_value{"Trap discovered: Acid"                  , 462},
		bool_value{"Trap discovered: Spring"                , 463},
		bool_value{"Trap discovered: Mine"                  , 464},
		bool_value{"Trap discovered: Turret"                , 465},
		bool_value{"Trap discovered: Forcefield"            , 466},
		bool_value{"Trap discovered: Crush trap"            , 467},
		bool_value{"Trap discovered: Ceiling trap"          , 468},
		bool_value{"Trap discovered: Spike ball"            , 469},
		bool_value{"Trap discovered: Lava"                  , 470},
		bool_value{"Character unlock: Yang"                , 649},
		bool_value{"Character unlock: Meat Boy"            , 650},
		bool_value{"Character unlock: Yellow"              , 651},
		bool_value{"Character unlock: The Jungle Warrior"  , 652},
		bool_value{"Character unlock: Purple"              , 653},
		bool_value{"Character unlock: Van Helsing"         , 654},
		bool_value{"Character unlock: Cyan"                , 655},
		bool_value{"Character unlock: Lime"                , 656},
		bool_value{"Character unlock: The Eskimo"          , 657},
		bool_value{"Character unlock: The Round Girl"      , 658},
		bool_value{"Character unlock: The Ninja"           , 659},
		bool_value{"Character unlock: The Viking"          , 660},
		bool_value{"Character unlock: The Round Boy"       , 661},
		bool_value{"Character unlock: The Cyclops"         , 662},
		bool_value{"Character unlock: The Robot"           , 663},
		bool_value{"Character unlock: The Golden Monk"     , 664},
		int_value{"Kill count: Snakes "                    , 665},
		int_value{"Kill count: Spiders "                   , 666},
		int_value{"Kill count: Bats "                      , 667},
		int_value{"Kill count: Caveman "                   , 668},
		int_value{"Kill count: Damsels "                   , 669},
		int_value{"Kill count: Shopkeepers "               , 670},
		int_value{"Kill count: (Blue) frogs "              , 671},
		int_value{"Kill count: Mantraps "                  , 672},
		int_value{"Kill count: Yetis "                     , 673},
		int_value{"Kill count: Ufos "                      , 674},
		int_value{"Kill count: Hawk man "                  , 675},
		int_value{"Kill count: Skeletons "                 , 676},
		int_value{"Kill count: Piranhas "                  , 677},
		int_value{"Kill count: Mummys "                    , 678},
		int_value{"Kill count: Monkeys  "                  , 679},
		int_value{"Kill count: Alien lords "               , 680},
		int_value{"Kill count: Ghost "                     , 681},
		int_value{"Kill count: Gaint spiders "             , 682},
		int_value{"Kill count: Jiang shis "                , 683},
		int_value{"Kill count: Vampires "                  , 684},
		int_value{"Kill count: Fire (orange) frogs "       , 685},
		int_value{"Kill count: Tunnelman "                 , 686},
		int_value{"Kill count: Old bitey "                 , 687},
		int_value{"Kill count: Scarabs "                   , 688},
		int_value{"Kill count: Yeti kings "                , 689},
		int_value{"Kill count: Aliens "                    , 690},
		int_value{"Kill count: Magma man "                 , 691},
		int_value{"Kill count: Vlads "                     , 692},
		int_value{"Kill count: Scorpions "                 , 693},
		int_value{"Kill count: Imps "                      , 694},
		int_value{"Kill count: Devils "                    , 695},
		int_value{"Kill count: Killer bees "               , 696},
		int_value{"Kill count: Anubises "                  , 697},
		int_value{"Kill count: Queen bees "                , 698},
		int_value{"Kill count: Bacterium "                 , 699},
		int_value{"Kill count: Cobra "                     , 700},
		int_value{"Kill count: Spinner spiders "           , 701},
		int_value{"Kill count: Gaint frogs "               , 702},
		int_value{"Kill count: Mammoths "                  , 703},
		int_value{"Kill count: Alien tanks "               , 704},
		int_value{"Kill count: Tiki man "                  , 705},
		int_value{"Kill count: Scorpion flys "             , 706},
		int_value{"Kill count: Snails "                    , 707},
		int_value{"Kill count: Croc man "                  , 708},
		int_value{"Kill count: Green knight "              , 709},
		int_value{"Kill count: Worm egg "                  , 710},
		int_value{"Kill count: Worm babys "                , 711},
		int_value{"Kill count: Alien queen "               , 712},
		int_value{"Kill count: Black knight "              , 713},
		int_value{"Kill count: Golden monkeys "            , 714},
		int_value{"Kill count: Succubus "                  , 715},
		int_value{"Kill count: Horse heads"                , 716},
		int_value{"Kill count: Ox face"                    , 717},
		int_value{"Kill count: Anubis II"                  , 718},
		int_value{"Kill count: Olmec"                      , 719},
		int_value{"Kill count: King yamas"                 , 720},
		int_value{"Death count: Snakes"                    , 721},
		int_value{"Death count: Spiders"                   , 722},
		int_value{"Death count: Bats"                      , 723},
		int_value{"Death count: Caveman"                   , 724},
		int_value{"Death count: Damsels"                   , 725},
		int_value{"Death count: Shopkeepers"               , 726},
		int_value{"Death count: (blue) frogs"              , 727},
		int_value{"Death count: Mantraps"                  , 728},
		int_value{"Death count: Yetis"                     , 729},
		int_value{"Death count: Ufos"                      , 730},
		int_value{"Death count: Hawk man"                  , 731},
		int_value{"Death count: Skeletons"                 , 732},
		int_value{"Death count: Piranhas"                  , 733},
		int_value{"Death count: Mummys"                    , 734},
		int_value{"Death count: Monkeys"                   , 735},
		int_value{"Death count: Alien lords"               , 736},
		int_value{"Death count: Ghost"                     , 737},
		int_value{"Death count: Gaint spiders"             , 738},
		int_value{"Death count: Jiang shis"                , 739},
		int_value{"Death count: Vampires"                  , 740},
		int_value{"Death count: Fire (orange) frogs"       , 741},
		int_value{"Death count: Tunnelman"                 , 742},
		int_value{"Death count: Old bitey"                 , 743},
		int_value{"Death count: Scarabs"                   , 744},
		int_value{"Death count: Yeti kings"                , 745},
		int_value{"Death count: Aliens"                    , 746},
		int_value{"Death count: Magma man"                 , 747},
		int_value{"Death count: Vlad"                      , 748},
		int_value{"Death count: Scorpions"                 , 749},
		int_value{"Death count: Imps"                      , 750},
		int_value{"Death count: Devils"                    , 751},
		int_value{"Death count: Killer bees"               , 752},
		int_value{"Death count: Anubis"                    , 753},
		int_value{"Death count: Queen bees"                , 754},
		int_value{"Death count: Bacteriums"                , 755},
		int_value{"Death count: Cobras"                    , 756},
		int_value{"Death count: Spinner spiders"           , 757},
		int_value{"Death count: Gaint frogs"               , 758},
		int_value{"Death count: Mammoths"                  , 759},
		int_value{"Death count: Alien tanks"               , 760},
		int_value{"Death count: Tiki man"                  , 761},
		int_value{"Death count: Scorpion flys"             , 762},
		int_value{"Death count: Snails"                    , 763},
		int_value{"Death count: Croc man"                  , 764},
		int_value{"Death count: Green knights"             , 765},
		int_value{"Death count: Worm eggs"                 , 766},
		int_value{"Death count: Worm babys"                , 767},
		int_value{"Death count: Alien queens"              , 768},
		int_value{"Death count: Black knight"              , 769},
		int_value{"Death count: Golden monkeys"            , 770},
		int_value{"Death count: Succubi"                   , 771},
		int_value{"Death count: Horse heads"               , 772},
		int_value{"Death count: Ox face"                   , 773},
		int_value{"Death count: Anubis II"                 , 774},
		int_value{"Death count: Olmec"                     , 775},
		int_value{"Death count: King yamas"                , 776},
		int_value{"Death count: Spike"                     , 777},
		int_value{"Death count: Arrow trap"                , 778},
		int_value{"Death count: Powder box"                , 779},
		int_value{"Death count: Boulder"                   , 780},
		int_value{"Death count: Tiki trap"                 , 781},
		int_value{"Death count: Acid"                      , 782},
		int_value{"Death count: Spring"                    , 783},
		int_value{"Death count: Mine"                      , 784},
		int_value{"Death count: Turret"                    , 785},
		int_value{"Death count: Forcefield"                , 786},
		int_value{"Death count: Crush trap"                , 787},
		int_value{"Death count: Ceiling trap"              , 788},
		int_value{"Death count: Lava"                      , 789},
		int_value{"Death count: Spike ball"                , 790},
		int_value{"Music volume"                           , 791},
		int_value{"SFX volume"                             , 792},
		int_value{"Damsel selected"                        , 793},
		int_value{"Screen brightness"                      , 794},
		int_value{"Player 1 character 0 - 20"              , 798},
		int_value{"Player 2 character 0 - 20"              , 799},
		int_value{"Player 3 character 0 - 20"              , 800},
		int_value{"Player 4 character 0 - 20"              , 801},
		bool_value{"Player 1 invert run"                   , 802},
		bool_value{"Player 2 invert run"                   , 803},
		bool_value{"Player 3 invert run"                   , 804},
		bool_value{"Player 4 invert run"                   , 805}
	}
{
}
